### ISSUE TITLE
URL Error even with the new Mewatch script

### ISSUE THREAD

**Issue by galpha20** [0x776b7364/toggle.sg-download#63]
Have Python 2.7 running on Windows 10 x64 with the latest FFMPEG file. Used the new Mewatch script here: https://github.com/ChinHuiHing/toggle.sg-download

I got this error when inputting this command:

> C:\Users\Galpha\Videos>download_toggle_video2.py -d https://www.mewatch.sg/en/series/my-grandpa/ep10/918933

`+++++++++++++++++++++++++++++++++++++
[*] Processing input 1 of 1 ...
+++++++++++++++++++++++++++++++++++++
[I] Toggle video https://www.mewatch.sg/en/series/my-grandpa/ep10/918933 detected
[D] Obtained mediaID = 918933
[D] Performing HTTP GET request on Toggle video URL ...
Traceback (most recent call last):
  File "C:\Users\Galpha\Videos\download_toggle_video2.py", line 511, in <module>
    main()
  File "C:\Users\Galpha\Videos\download_toggle_video2.py", line 483, in main
    records_to_enqueue = process_url(input_url)
  File "C:\Users\Galpha\Videos\download_toggle_video2.py", line 176, in process_url
    return process_video_url(url)
  File "C:\Users\Galpha\Videos\download_toggle_video2.py", line 212, in process_video_url
    t_video_url_resp = urllib_request.urlopen(t_video_url_req).read()
  File "C:\Python27\lib\urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 391, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 409, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1181, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "C:\Python27\lib\urllib2.py", line 1148, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 1] _ssl.c:499: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version>`

Please help, thank you.

**Comment by ownerowner** [comment]
It works well ，i  tried just now

**Comment by galpha20** [comment]
Still not working...I'm using Python 2.7 on Windows 10 x64 and the latest ffmpeg.exe. I have the following in my "C:\Users\galpha\Videos" folder:

download_toggle_video2.py and ffmpeg.exe

Python 2.7 is in "C:\Python27\" folder.

**Comment by prokiller1199** [comment]
> Have Python 2.7 running on Windows 10 x64 with the latest FFMPEG file. Used the new Mewatch script here: https://github.com/ChinHuiHing/toggle.sg-download
> 

This works well for user ChinHuiHing scripts. Tested Windows 10 x64 April 1st.

**Comment by ChinHuiHing** [comment]
@galpha20 I think maybe u can try using python 3.6.
